### ISSUE TITLE
BoolOr functionality

### ISSUE THREAD

**Issue by nomicnetworks** [aykut/django-aggregates#1]
Thanks for this contribution!  Question about the BoolOr function: It seems to only accept a column name as an argument ... do you have plans to allow expressions that evaluate to true or false, too, as is possible natively in Postgres?  For example: BoolOr('foo is not null')

Thanks!

**Comment by aykut** [comment]
Hi,

Actually, you can use `extra`:
`User.objects.extra(select={'boolar': 'BOOL_OR(foo is null)'}).values('boolar')`

Or see #2 .

Thank you.

**Comment by nomicnetworks** [comment]
Thanks for your help, and for the quick code addition.  I'll give it a try.

Ted
